language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: firebase
  token:
    secure: 'A9W6jjNHyfj8ylY+sbQYCnIFha1vwa5HVQOy/QFMFAi/sYsqjg8lZAee36EBlMhO+/NhcCkEX8vVnFyDrWI80kl+bbLhoSDagcbigPoAfBRaVjHq/zaMkKfRq4eQVLd7pIsCsyGnN1RjujwyWNVnhJnD/S3N0WBS3aV4eb+Gyw869xYGOi8SNmW/cRJ6Tl9s0vgKJQXAhZa+08kI00MrOY8048XCsEoaXJtYDEByNgo9O3mDojTJszqlz+JqsiHbSJEmbaGbvidJf40hR/d0WLE7+TXX+4p5j7nwVol2obEZoFLwj/+4L7qgFrkaSZ0LNsx6EBdDfDZ8BoYLqmi4MFTpWzDqb7QiBJqebAv1IIxvlIetwgkMQpYHF5kcIXvm0WhQZfYvBOkSnWBZSjFrdNIMoPdvdAWdkb9JNWxwjq6XAwW8P8KFwUEJRJGPfKQ68VUQ8e2+Q0m2SzQftKSrdVDR3hV2g5+Obonewma+3H9qALveb4pDrLpId2XGa5frgDwxQ1GLJEkgz+T8jyedCG0vzssfaTEghOeQqXi8S1jQqr2bT9csuqbGQ4vsvJtg6kH2IHRE9GXI7zDHRAOwP0rvx+4nqeko08FEZGVQCmFdyf+TFixe/sU+7DHXyoDILV58iKuGCluP2nYt9OE3l0+P8qWeummPwbLKhXk1VKA='
  project: 'duffel'
